name: Dynamic Helm Test Matrix

on:
  push:
  workflow_dispatch:

jobs:
  setup-matrix:
    name: Generate Matrix
    container:
      image: ${{ vars.helm_image }}
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.find-folders.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Find directories and format JSON
        id: find-folders
        run: |
          DIRS=$(find ./src/test/helm/* -maxdepth 0 -type d -exec basename {} \;)
          JSON_ARRAY=$(echo "$DIRS" | jq -R -s -c 'split("\n") | del(.[] | select(. == ""))')
          
          echo "Discovered folders: $JSON_ARRAY"
          echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT

  run-helm-tests:
    name: Test folder - ${{ matrix.folder }}
    container:
      image: ${{ vars.helm_image }}
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.setup-matrix.outputs.folders) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Step 1: Linting ${{ matrix.folder }}"
        run: |
          echo "Processing directory: ./src/test/helm/${{ matrix.folder }}"
