name: Build Branch

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.mvn_image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Copy m2 settings
        env:
          MTWOS: ${{ vars.M2_SETTINGS_PULL_PROXY }}
        run: |
          mkdir -p ~/.m2
          printf "$MTWOS" > ~/.m2/settings.xml
      - name: Set Release Version
        run: mvn -B versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false
      - name: Build Release
        run: mvn package -Dnative -Dquarkus.native.remote-container-build=true
      - name: Login to Docker Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: abell.registry.macslabs.de
          username: ${{ secrets.DR_ABELL_USER }}
          password: ${{ secrets.DR_ABELL_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./src/main/docker/Dockerfile.native-micro
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_build.outputs.tags }}
          labels: ${{ steps.meta_build.outputs.labels }}
