name: Build Branch

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.mvn_image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Copy m2 settings
        env:
          MTWOS: ${{ vars.M2_SETTINGS_PULL_PROXY }}
        run: |
          mkdir -p ~/.m2
          printf "$MTWOS" > ~/.m2/settings.xml
      - name: Set Release Version
        run: mvn -B versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false
      - name: Build Release
        run: mvn package -Dnative -Dquarkus.native.remote-container-build=true
      - name: Build Micro Image
        run: docker build -f src/main/docker/Dockerfile.native-micro -t quarkus/timed-alert:${{ github.ref_name }} .
