apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-configuration
  labels:
    app: {{.Release.Name}}
data:
  UID: "1000"
  GID: "1000"
  startHour: "{{.Values.deployment.configuration.startHour}}"
  startMinute: "{{.Values.deployment.configuration.startMinute}}"
  endHour: "{{.Values.deployment.configuration.endHour}}"
  endMinute: "{{.Values.deployment.configuration.endMinute}}"
  dayOfAlert: "{{.Values.deployment.configuration.dayOfAlert}}"